device: cuda:0

run_train:
  epoch: 100
  grad_enabled: False

dataset:
  S:
    base: /dgx/github/DVC/data/dataset
    query:
      - product_type == 'H' &
        is_anomaly_image == 1 &
        is_train == 1 &
        is_test == 0
  C:
    base: /dgx/github/DVC/data/dataset
    query:
      - product_type == 'H' &
        is_anomaly_image == 1 &
        is_train == 1 &
        is_test == 0
      - product_type == 'H' &
        is_anomaly_image == 0 &
        is_train == 1 &
        is_test == 0
  test:
    base: /dgx/github/DVC/data/dataset
    query:
      - product_type == 'H' &
        is_anomaly_image == 1 &
        is_train == 0 &
        is_test == 1
      - product_type == 'H' &
        is_anomaly_image == 0 &
        is_train == 0 &
        is_test == 1

dataloader:
  S:
    batch_size: 16
    shuffle: True
  C:
    batch_size: 16
    shuffle: True
  test:
    batch_size: 1
    shuffle: True

model:
  S:
    name: DeepLabV3
    pth:
    args:
      pretrained: True
      num_classes: 2
  C:
    name: VGG19
    pth:
    args:
      pretrained: True
      in_channels: 2
      out_features: 2

augs:
  height: 256
  width: 256
  S:
    yaml: /dgx/github/SSAD/ssad/conf/augs/train_semseg.yaml
    args:
      Resize:
        height: ${augs.height}
        width: ${augs.width}
  C:
    yaml: /dgx/github/SSAD/ssad/conf/augs/train_classifier.yaml
    args:
      Resize:
        height: ${augs.height}
        width: ${augs.width}
  test:
    yaml: /dgx/github/SSAD/ssad/conf/augs/test.yaml
    args:
      Resize:
        height: ${augs.height}
        width: ${augs.width}

optimizer:
  S:
    name: Adam
    args:
      lr: 0.0002
      weight_decay: 0.00001
  C:
    name: Adam
    args:
      lr: 0.0002
      weight_decay: 0.00001

criterion:
  S:
    name: CrossEntropy2D
    args:
      reduction: mean
  C:
    name: CrossEntropyLoss
    args:
