device: cuda:0

train:
  augs: /dgx/github/DeepLabV3/deeplabv3/conf/augs/train_augs.yaml
  epochs: 10
  batch_size: 256
  optim:
    name: Adam
    lr: 0.0002
    weight_decay: 0.00001
  criterion:
    name: MSELoss

test:
  augs: /dgx/github/DeepLabV3/deeplabv3/conf/augs/test_augs.yaml
  batch_size: 32
